version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apipg
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - apipg

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - apipg

  app:
    build: .
    command: yarn start
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=apipg
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db
    ports:
      - "3333:3333"
    links:
      - redis
      - db
    volumes:
      - .:/user/app
    networks:
      - apipg

  queue:
    build: .
    command: yarn queue
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=apipg
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    volumes:
      - .:/user/app
    networks:
      - apipg

volumes:
  postgres-data:

networks:
  apipg:
