version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=apipg
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - apipg

  app:
    build: .
    command: npm start
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=apipg
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db
    ports:
      - "3333:3333"
    links:
      - redis
      - db
    volumes:
      - .:/user/app
    networks:
      - apipg

volumes:
  postgres-data:

networks:
  apipg:
